# TODO: 运行时配置
settings:
  # 配置文件版本: 年-月日
  config-version: 2023-0109
  language: zh_CN
  # 调试模式
  debug: true
  # 服务器的列表及其前缀s
  server-list:
    # - example-server:
    #     prefix: example
    #     permission: redirect.example
    - LoginServer:
        prefix:
        permission: null
    - LoginServer_be:
        prefix: BxE
        permission: null
  #
  # 匹配设置
  match:
    enabled: true
    # 玩家名称前缀匹配
    player-name-prefix:
      enabled: true
      # 玩家名称前缀分隔符号
      prefix-divider: "."
    # 玩家 UUID 匹配
    player-uuid:
      enabled: true
      # 玩家 UUID 匹配
      uuid-match-list:
        # - Example: $$$$$$$$-$$$$-A$$$-B$$$-$$$$$$$$$$$$
        #   enabled: false
        - bxe-player: 00000000-0000-0000-$$$$-$$$$$$$$$$$$
          enabled: true
      # 玩家 UUID 匹配模式
      match-pattern: "[a-zA-Z0-9]"
  # 大厅命令设置
  hub:
    enabled: true


  # TODO:
  # 重定向设置
  #redirect:
  #  # /redirect 命令的别名
  #  aliases: [ goto ]
  #  # 重定向前的延时 (秒)
  #  redirect-delay-in-seconds: 0.5
  #  # 自动重定向前的延时 (秒)
  #  auto-redirect-delay-in-seconds: 5
