# CatWorldSpace-System 插件的配置文件

# 配置文件版本: 年-月日
config-version: 2023-0225
# 调试模式
debug: true
# 显示语言
language: zh_CN

# 功能设置
settings:
  # 插件主命令设置
  system:
    command-name: system
    command-permission: cws-system.*
    command-alias: [ cws ]
  # 服务器的列表及其前缀
  server-list:
    # - example-server:
    #     permission: redirect.example-server
    #     redirect-prefix: Example
    - LoginServer:
        permission:
        redirect-prefix: default
    - LoginServer_be:
        permission:
        redirect-prefix: BxE
  # 匹配设置
  prefix-uuid-match:
    enabled: true
    # 玩家名称前缀分隔符号
    prefix-separator: "."
    # 玩家 UUID 匹配
    uuid-match:
      enabled: true
      # 玩家 UUID 匹配
      uuid-match-list:
        # - Example: $$$$$$$$-$$$$-A$$$-B$$$-$$$$$$$$$$$$
        - BxE: 00000000-0000-0000-$$$$-$$$$$$$$$$$$
      # 玩家 UUID 匹配模式
      match-pattern: "[a-zA-Z0-9]"
  # 大厅命令设置
  hub:
    enabled: true
    command-name: hub
    command-permission: hub
    command-alias: [lobby]

  # TODO:
  # 重定向设置
  #redirect:
  #  # /redirect 命令的别名
  #  aliases: [ goto ]
  #  # 重定向前的延时 (秒)
  #  redirect-delay-in-seconds: 0.5
  #  # 自动重定向前的延时 (秒)
  #  auto-redirect-delay-in-seconds: 5
