# CatWorldSpace-System 插件的配置文件

# 配置文件版本: 年-月日
config-version: 2023-0117
# 调试模式
debug: true
# 显示语言
language: zh_CN

# 功能设置
settings:
  # 服务器的列表及其前缀
  server-list:
    # - example-server:
    #     permission: redirect.example
    - LoginServer:
        permission:
    - LoginServer_be:
        permission:
  # 插件主命令设置
  system:
    name: system
    permission: cws-system.*
    alias: [ cws ]
  # 匹配设置
  prefix-uuid-match:
    enabled: true
    # 玩家名称前缀分隔符号
    prefix-divider: "."
    # 玩家 UUID 匹配
    match-uuid:
      enabled: true
      # 玩家 UUID 匹配
      uuid-match-list:
        # - Example: $$$$$$$$-$$$$-A$$$-B$$$-$$$$$$$$$$$$
        - bxe-player: 00000000-0000-0000-$$$$-$$$$$$$$$$$$
      # 玩家 UUID 匹配模式
      match-pattern: "[a-zA-Z0-9]"
    redirect-server-list:
      -
        prefix: BxE
        server : LoginServer_be
      -
        prefix:
        server: LoginServer
  # 大厅命令设置
  hub:
    name: hub
    enabled: true
    permission: hub
    alias: [lobby]

  # TODO:
  # 重定向设置
  #redirect:
  #  # /redirect 命令的别名
  #  aliases: [ goto ]
  #  # 重定向前的延时 (秒)
  #  redirect-delay-in-seconds: 0.5
  #  # 自动重定向前的延时 (秒)
  #  auto-redirect-delay-in-seconds: 5
